### ISSUE TITLE
Performance improvement Bing/OSM

### ISSUE THREAD

**Issue by rossbernet** [geotrellis/geotrellis-osm-diff-demo#8]
Let's see if this can be sped up.

https://demos.azavea.com/building-footprint-comparison/#3.5/38/-97

Some discussion during standup suggested perhaps removing / simplifying geometry could have some significant performance gains.

**Comment by CloudNiner** [comment]
This could use some discussion since I’m pretty sure the perf issue is just because we’re drawing so many geometries client side. Is this really something we want to burn time on?

Delaware doesn't have enough geoms to trigger this issue. So in order to debug we need to generate geojson with enough geometries to approximately reproduce the slowness -- or reuse California or CONUS (Cali likely isn't large enough either). Once we have geojson, we need to regenerate a large mbtiles file and then export+push tiles each time we do. This is a long debug cycle (on the order of 1-2 hrs) and with two points, maybe we could get a few iterations in tops.

Unless you're thinking of changes to the Spark code, but I think that's misdirected. It's up to the Tippecanoe step to filter/simplify geometries enough to fit into the tiles.

This issue also goes against the request I had earlier to generate polygons to a high zoom level, specifically so that they aren't simplified. If its the middle zoom levels that are slow, then perhaps a first pass is to just tweak the simplification parameter, test it on a smaller dataset like delaware and then re-run once and hope for the best.

**Comment by CloudNiner** [comment]
@rossbernet I regenerated the static diff tiles using the following additional Tippecanoe options:
- `-ac (--coalesce)`: Turns on coalescing such that sequential features (polygons in our case) with identical attributes are packed together into a single feature (multipolygon)
- `-ao (--reorder)`: Reorders features to put ones with the same attributes in sequence
- `-ah (--hilbert)`: Put features in Hilbert Curve order instead of the usual Z-Order. This improves the odds that spatially adjacent features will be sequentially adjacent

The Netlify preview is up at: https://deploy-preview-27--azavea-demos.netlify.com/, initial tests are promising.

The additional of `--hilbert` doesn't make a big difference, but the combination of `--coalesce` and `--reorder` cuts a good percentage of the tile sizes in ~half and combines geometries appropriately. Those buildings with unique names and/or building types are left as polygons, otherwise most geoms are combined into a single multipolygon.

### Before and after network requests for the same extent

![Screen Shot 2019-07-10 at 9 15 51 AM](https://user-images.githubusercontent.com/1818302/60973842-fd7d1b80-a2f6-11e9-8532-c0b1941fe438.png)
![Screen Shot 2019-07-10 at 9 13 03 AM](https://user-images.githubusercontent.com/1818302/60973844-fd7d1b80-a2f6-11e9-8435-7cab66a04598.png)

### Feature changes with new options

#### Example coalesced multipolygon
![Screen Shot 2019-07-10 at 9 20 00 AM](https://user-images.githubusercontent.com/1818302/60974057-619fdf80-a2f7-11e9-916d-d8902aa97ccd.png)

#### Example unique feature left alone
![Screen Shot 2019-07-10 at 9 20 22 AM](https://user-images.githubusercontent.com/1818302/60974046-5d73c200-a2f7-11e9-8628-fac2382fbeb5.png)

**Comment by CloudNiner** [comment]
Still a bit slow for now, but this time box is complete. Further optimizations might look at increasing the number of geometries we drop in the middle zoom levels.

**Comment by CloudNiner** [comment]
Also unclear ATM what the value is in keeping the mbtiles file around, but its here for now:
```
s3://geotrellis-demo/osm-buildings-diff/mbtiles/united-states-diff-v2.0.mbtiles
```

Which was generated with:
```
time cat ./path/to/geojson/part-*.txt | tippecanoe -o united-states-diff-v2.mbtiles \
    -l diff -z14 --drop-densest-as-needed \
    --coalesce --reorder --hilbert \
    --force -s EPSG:3857 -P
```

**Comment by rossbernet** [comment]
> Also unclear ATM what the value is in keeping the mbtiles file around, but its here for now:

Which ones? The old ones, or the newer, faster ones?

This certainly feels quite a bit faster. I think we are ready for pushing it public.

**Comment by CloudNiner** [comment]
The link above is to the newer, cleaned up mbtiles file.

**Comment by CloudNiner** [comment]
@rossbernet in case you don't get notifications for azavea/demos, I assigned you to https://github.com/azavea/demos/pull/27. It needs a 👍 in order to merge.
